version: "3.8"
services:
    app: 
      image: odos-backend:Dev
      depends_on:
        - data
      ports:
        - "8081:8081"
      networks:
        - data_net
      env_file: 
        - .env

    data:
      image: postgres:12
      restart: always
      ports: 
        - "5432:5432"
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - data_net
      env_file:
        - .env 
    

networks:
    data_net:  

volumes: 
    postgres:
