#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="build-image"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/.env

cd $PROJECT_DIR
docker build -t $IMG_NAME:$IMG_TAG .