#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="postgres"
SCRIPT_DES=$''
PROJECT_DIR=$SCRIPT_DIR/../../..
source $PROJECT_DIR/.env

docker run --name $APPLICATION-postgres \
            --publish 5432:5432 \
            --env-file $PROJECT_DIR/.env \
            --detach \
            postgres:12